version: '3'

services:
    lambda-app:
        build:
            context: ./lambda-app/
            dockerfile: Dockerfile
        expose:
            - 3000
        ports:
            - 3000:3000
        restart: on-failure
        volumes:
            - ./lambda-app/:/app

    # here could be the other applications
